version: '3.3'
services:
  php-apache:
    image: php:7.2.16-apache
    build: _docker/php-apache
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
    links:
      - 'db'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db:
