version: '3.6'
services:

  mail:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  php-apache:
    image: php:7.2.16-apache
    build: _docker/php-apache
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
    environment:
      VIRTUAL_HOST: test.local
    links:
      - 'db'
      - 'mail'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db:
