version: '3.6'
services:

  mail:
    image: mailhog/mailhog
    container_name: mail_catcher
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  php-apache:
    image: php:7.2.16-apache
    container_name: typo3_instance
    build: _docker/php-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
    environment:
      VIRTUAL_HOST: test.local
    links:
      - 'db'
      - 'mail'

  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  solr:
    image: solr
    container_name: solr_search
    ports:
      - 8983:8983
    volumes:
      - ./_docker/solr:/opt/solr/server/mycores
    entrypoint:
      - bash
      - -c
      - precreate-core core-de; precreate-core core-en; exec solr -f

volumes:
  db:
